version: '3.8'
services:

  php:
    image: serversideup/php:8.1.2-unit-bookworm
    environment:
      SSL_MODE: "off"
      # LOG_LEVEL: "debug"
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html/
    networks:
      - development
    # entrypoint: ""

networks:
  development: