services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SSL_MODE: "off"
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - .:/var/www/html/
    networks:
      - development
    # entrypoint: ""

networks:
  development: