services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PHP_DATE_TIMEZONE: "Arctic/Longyearbyen"
      PHP_DISPLAY_ERRORS: "On"
      PHP_DISPLAY_STARTUP_ERRORS: "On"
      PHP_ERROR_REPORTING: "32767"
      PHP_MAX_EXECUTION_TIME: "4000"
      PHP_MEMORY_LIMIT: "512M"
      PHP_POST_MAX_SIZE: "1000M"
      PHP_UPLOAD_MAX_FILESIZE: "1000M"
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - .:/var/www/html/
    networks:
      - development
    # entrypoint: ""

networks:
  development: