version: '3.8'
services:

  php:
    image: serversideup/php-pro:8.2-nginx-unit-bookworm
    environment:
      SSL_MODE: mixed
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html/
    networks:
      - development

networks:
  development: