version: '3.8'
services:

  php:
    image: serversideup/php:beta-8.1-fpm-nginx
    environment:
      PHP_DISPLAY_ERRORS: On
      SSL_MODE: "off"
      PHP_SESSION_COOKIE_SECURE: 1
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html/
    networks:
      - development
    # # 🔥 Uncomment for debugging
    # environment:
    #   DEBUG_OUTPUT: "true"

networks:
  development: