version: '3.8'
services:

  php:
    build:
      context: .
      target: base
    environment:
      PHP_DISPLAY_ERRORS: On
      SSL_MODE: "mixed"
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html/
    networks:
      - development

networks:
  development: