version: '3.8'
services:

  php:
    image: serversideup/php:8.1-fpm-nginx-v2.2.1
    environment:
      PHP_MAX_EXECUTION_TIME: "300"
      PHP_MEMORY_LIMIT: "1024M"
      AUTORUN_ENABLED: false
      SSL_MODE: "off"
      PHP_DATE_TIMEZONE: "Asia/Riyadh"
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html/
    networks:
      - development
    # # 🔥 Uncomment for debugging
    # environment:
    #   DEBUG_OUTPUT: "true"

networks:
  development: